name: Deploy

on:
  push:
    branches:
      - master
jobs:
  buid:
    runs-on: windows-latest

    steps:

    - name: Checkout
      users: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install MAUI Workload
      run: dotnet workload install maui
    
    - name: Restore
      run: dotnet restore
      working-directory: .\InspectorDemoApp

    - name: Build
      run: dotnet build -c Release -f:net8.0-windows10.019041.0
      working-directory: .\InspectorDemoApp

    - name: Test
      run: dotnet test -c Release -f:net8.0-windows10.019041.0
      working-directory: .\InspectorDemoApp

    - name: Publish
      run: dotnet publish -c Release -f:net8.0-windows10.0.19041.0 /p:GenerateAppxPackageOnBuild=true
      working-directory: .\InspectorDemoApp
    
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
       name: Build
       path: ./InspectorDemoApp/bin/Release/net8.0-windows10.0.19041.0/win10-x64/AppPackages/**/*.msix
    



