# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install MAUI Workload
      run: dotnet workload install maui   
    - name: Restore
      run: dotnet restore
      working-directory: InspectorDemoApp/InspectorDemoApp

    - name: Build
      run: dotnet build -c Release -f:net8.0-windows10.0.19041.0
      working-directory: InspectorDemoApp/InspectorDemoApp

    - name: Decode Signing Certificate
      run: |
       echo "${{ secrets.SIGNING_CERTIFICATE_BASE_64_CONTENT }}" > cerf.asc
       certutil -decode cerf.asc cerf.pfx

     
    - name: Install Signing Certificate 
      run: certutil -user -p ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }} -Silent -importpfx cerf.pfx NoRoot


    - name: Publish
      run: dotnet publish -c Release -f:net8.0-windows10.0.19041.0 /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint=${{ secrets.SIGNING_CERTIFICATE_THUMBPRINT }}
      working-directory: InspectorDemoApp/InspectorDemoApp
      
    - name: List Build Output
      run: dir InspectorDemoApp/InspectorDemoApp/bin/Release/net8.0-windows10.0.19041.0/win10-x64/AppPackages
      
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Build
        path: InspectorDemoApp/InspectorDemoApp/bin/Release/net8.0-windows10.0.19041.0/win10-x64/AppPackages/**/*.msix
              InspectorDemoApp/InspectorDemoApp/bin/Release/net8.0-windows10.0.19041.0/win10-x64/AppPackages/**/*.cer
