# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write 

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install MAUI Workload
      run: dotnet workload install maui   

    - name: Restore
      run: dotnet restore
      working-directory: InspectorDemoApp/InspectorDemoApp

    - name: Build
      run: dotnet build -c Release -f:net8.0-windows10.0.19041.0
      working-directory: InspectorDemoApp/InspectorDemoApp

    - name: Decode Signing Certificate
      run: |
       echo "${{ secrets.SIGNING_CERTIFICATE_BASE_64_CONTENT }}" > cerf.asc
       certutil -decode cerf.asc cerf.pfx

    - name: Install Signing Certificate 
      run: certutil -user -p ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }} -Silent -importpfx cerf.pfx NoRoot

    - name: Publish
      run: dotnet publish -c Release -f:net8.0-windows10.0.19041.0 /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint=${{ secrets.SIGNING_CERTIFICATE_THUMBPRINT }}
      working-directory: InspectorDemoApp/InspectorDemoApp
   
    - name: List Build Output
      run: dir InspectorDemoApp/InspectorDemoApp/bin/Release/net8.0-windows10.0.19041.0/win10-x64/AppPackages
    - name:  Extract Version
      id: extractVersion
      shell: pwsh
      run: |
        $xml =[Xml] (Get-Content InspectorDemoApp\InspectorDemoApp\InspectorDemoApp.csproj)
        [string] $version = [Version]$xml.Project.PropertyGroup.ApplicationDisplayVersion
        echo "version=$($version)" >> $env:GITHUB_OUTPUT
    - name: Create Tag 
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN}}
        script: |
          github.rest.git.createRef({
             owner: context.repo.owner,
             repo: context.repo.repo,
             sha: context.sha,
             ref:'refs/tags/v${{stpes.extractVersion.outputs.version}}'
             
           })
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with: 
        tag_name: v${{ steps.extractVersion.outputs.version }}
        files: |
          InspectorDemoApp/InspectorDemoApp/bin/Release/net8.0-windows10.0.19041.0/win10-x64/AppPackages/InspectorDemoApp_${{ steps.extractVersion.outputs.version }}_Test/InspectorDemoApp_${{ steps.extractVersion.outputs.version }}_x64.msix
          InspectorDemoApp/InspectorDemoApp/bin/Release/net8.0-windows10.0.19041.0/win10-x64/AppPackages/InspectorDemoApp_${{ steps.extractVersion.outputs.version }}_Test/InspectorDemoApp_${{ steps.extractVersion.outputs.version }}_x64.cer
 

